import tkinter as tk
from tkinter import filedialog, messagebox
import csv
import sys

class VGAPipBoyViewer(tk.Tk):
    def __init__(self, csv_data):
        super().__init__()
        self.csv_data = csv_data
        self.current_step = 0
        self.max_step = len(csv_data) - 1

        self.title("RV32I VGA Pip-Boy Monitor Viewer")
        self.configure(bg="#001100")
        
        # UI Setup
        self.grid_rowconfigure(0, weight=1)
        self.grid_columnconfigure(0, weight=1)
        
        # 80x30 text area
        self.text_area = tk.Text(
            self, 
            width=80, 
            height=30, 
            bg="#002200", 
            fg="#39ff14", 
            font=("Consolas", 14, "bold"),
            state="disabled",
            relief="flat",
            padx=10,
            pady=10
        )
        self.text_area.grid(row=0, column=0, padx=20, pady=20)
        
        # Instruction Label
        instruction_frame = tk.Frame(self, bg="#001100")
        instruction_frame.grid(row=1, column=0, pady=(0, 20))
        
        tk.Label(
            instruction_frame, 
            text="< LEFT ARROW : Step Backward | RIGHT ARROW : Step Forward >", 
            bg="#001100", 
            fg="#39ff14", 
            font=("Consolas", 12, "bold")
        ).pack()

        # Bind Keys
        self.bind("<Right>", self.step_forward)
        self.bind("<Left>", self.step_backward)
        
        # Render initial step
        self.render_screen()

    def step_forward(self, event):
        if self.current_step < self.max_step:
            self.current_step += 1
            self.render_screen()

    def step_backward(self, event):
        if self.current_step > 0:
            self.current_step -= 1
            self.render_screen()

    def render_screen(self):
        row_data = self.csv_data[self.current_step]
        
        # Expected CSV Headers (generated by gen_tests.py):
        # Instruction,PC,Current Instruction,Result,rs1,rs2,x0...x31
        # If it's a "--- ROLLBACK INITIATED ---" row, handle gracefully
        
        if row_data[0].startswith("---"):
            content = [" " * 80 for _ in range(30)]
            msg = "ROLLBACK INITIATED"
            content[14] = msg.center(80)
            self._update_text(content)
            return

        pc = row_data[1]
        inst_hex = row_data[2]
        alu_res = row_data[3]
        rs1 = row_data[4]
        rs2 = row_data[5]
        
        regs = row_data[6:38]
        if len(regs) < 32:
            regs = ["OFF"] * 32

        # Build 30 lines of 80 characters
        lines = []
        
        # Top Border
        lines.append("+" + "-"*78 + "+")
        
        # Header Info
        header_text = f" RV32I HARDWARE MONITOR | STEP: {self.current_step}/{self.max_step} "
        lines.append("|" + header_text.center(78) + "|")
        lines.append("|" + " "*78 + "|")
        
        # PC and Inst
        pc_str = f" PC: {pc} "
        inst_str = f" INST: {inst_hex} "
        lines.append("|  " + pc_str.ljust(35) + inst_str.ljust(41) + "|")
        
        # ALU and RS
        alu_str = f" ALU_RES: {alu_res} "
        rs_str = f" rs1: {rs1}   rs2: {rs2} "
        lines.append("|  " + alu_str.ljust(35) + rs_str.ljust(41) + "|")
        
        lines.append("|" + " "*78 + "|")
        lines.append("|" + " --- REGISTERS ".ljust(78, "-") + "|")
        lines.append("|" + " "*78 + "|")
        
        # Register Grid (4 columns, 8 rows)
        for i in range(8):
            row_str = " |  "
            for col in range(4):
                reg_idx = i + (col * 8)
                val = regs[reg_idx] if reg_idx < len(regs) else "OFF"
                reg_name = f"x{reg_idx}".ljust(3)
                row_str += f"{reg_name}:{val}    "
            row_str = row_str.ljust(79) + "|"
            lines.append(row_str)
            
        lines.append("|" + " "*78 + "|")
        
        # Status / Assembly
        lines.append("|" + " --- DECODED ASSEMBLY ".ljust(78, "-") + "|")
        lines.append("|" + " "*78 + "|")
        asm_str = f" > {row_data[0]} "
        lines.append("|" + asm_str.center(78) + "|")
        
        # Pad remaining lines to exactly 30
        while len(lines) < 29:
            lines.append("|" + " "*78 + "|")
            
        lines.append("+" + "-"*78 + "+")
        
        self._update_text(lines)

    def _update_text(self, lines):
        self.text_area.config(state="normal")
        self.text_area.delete("1.0", tk.END)
        self.text_area.insert("1.0", "\n".join(lines))
        self.text_area.config(state="disabled")


def main():
    root = tk.Tk()
    root.withdraw() # Hide root window
    
    file_path = filedialog.askopenfilename(
        title="Select RV32I Test CSV File",
        filetypes=[("CSV Files", "*.csv"), ("All Files", "*.*")]
    )
    
    if not file_path:
        sys.exit(0)
        
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            reader = csv.reader(f)
            data = list(reader)
            
        if len(data) < 2:
            messagebox.showerror("Error", "CSV file is empty or invalid.")
            sys.exit(1)
            
        # Remove header row
        headers = data[0]
        rows = data[1:]
        
        app = VGAPipBoyViewer(rows)
        app.mainloop()
        
    except Exception as e:
        messagebox.showerror("Error", f"Failed to load CSV:\n{str(e)}")

if __name__ == "__main__":
    main()
